data en game opgesteld
zuyd-projects/synergy pull request #21
Opened 2024-11-01 09:01 UTC by broertje-cloud

## 🎟️ Issue
 Linear ticket BEN-16 for example 

## ✨ Description
 Game,Question en answer aanngepast

## 🕵 Background
 Explain why this change is being made

## 📝 Resources
Add notes and documentation links where relevant

2024-11-01 09:13 UTC, Underlyingglitch requested changes

2024-11-01 09:13 UTC, Underlyingglitch commented on ExotischNederland/Models/Answer.cs
> +        private Answer(int id, Question question, string text, bool correct)
Please use the constructor used in other files (with the Dictionary<string, object>

2024-11-01 09:13 UTC, Underlyingglitch commented on ExotischNederland/Models/Answer.cs
> +        {
Careful with the line indentation here. The { and } should be 1 tab further for readability

2024-11-01 09:13 UTC, Underlyingglitch commented on ExotischNederland/Models/Game.cs
> +        private Game(int id, Route route, string title, string description)
Use the other constructor here too

2024-11-01 09:13 UTC, Underlyingglitch commented on ExotischNederland/Models/Game.cs
> +        {
Watch the indentation here

2024-11-01 09:13 UTC, Underlyingglitch commented on ExotischNederland/Models/Route.cs
Why are these changes made? Does the Route need to be public? Id should never be settable from another class

2024-11-01 10:54 UTC, broertje-cloud reviewed
feedback aangepast

2024-11-01 11:20 UTC, Underlyingglitch requested changes
Unfortunately it still needs some work. I added some code refactors, so pull this branch first and check out what changed. For example: answers are added to the list on Question, but never stored/retrieved in the database. Same goes for the relationship Question - Game

2024-11-03 18:15 UTC, closed without merging

2024-11-03 23:29 UTC, broertje-cloud reviewed
ok